# Generated by Django 4.2.19 on 2025-03-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_booking_which_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='which_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], default=0, max_length=200),
        ),
    ]
