# Generated by Django 4.2.19 on 2025-03-03 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, null='tempSlug', unique=True)),
                ('movie_desc', models.TextField()),
                ('movie_image', models.TextField(max_length=200, null='tempImg1')),
                ('movie_image_desc', models.TextField(max_length=200, null='tempImgDesc')),
                ('meal_name', models.CharField(max_length=200, unique=True)),
                ('listed_on', models.DateTimeField(auto_now_add=True)),
                ('available', models.IntegerField(choices=[(0, 'Free-Space'), (1, 'Fully-Booked')], default=0)),
                ('listing_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_title', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
