# Generated by Django 4.2.19 on 2025-03-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
        migrations.AddField(
            model_name='movie',
            name='available',
            field=models.IntegerField(choices=[(0, 'Free-Space'), (1, 'Fully-Booked')], default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_image',
            field=models.TextField(max_length=200, null='tempImg1'),
            preserve_default='tempImg1',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_image_desc',
            field=models.TextField(max_length=200, null='tempImgDesc'),
            preserve_default='tempImgDesc',
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(max_length=200, null='tempSlug', unique=True),
            preserve_default='tempSlug',
        ),
    ]
