# Generated by Django 4.2.19 on 2025-03-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='listing_author',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
        migrations.AddField(
            model_name='movie',
            name='available',
            field=models.IntegerField(choices=[(0, 'Free-Space'), (1, 'Fully-Booked')], default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_image',
            field=models.TextField(default='tempImg', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_image_desc',
            field=models.TextField(default='tempImgDesc', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='tempSlug', max_length=200, unique=True),
        ),
    ]
