# Generated by Django 4.2.19 on 2025-03-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_year',
            field=models.TextField(max_length=200, null='tempYear'),
            preserve_default='tempYear',
        ),
    ]
